AWSTemplateFormatVersion: "2010-09-09"
Description: Nexus Repository Resources
Parameters:
  AmiId:
    Type: String
    Description: "Amazon Machine Image ID"
  Ec2Port:
    Type: String
    Description: "The port the EC2 instance's application listens on"
  Ec2Type:
    Type: String
    Description: "The EC2 Instance Type"
  ElbPort:
    Type: String
    Description: "The port the ELB listens on"
  ElbTier:
    Type: String
    Default: public
    AllowedValues:
      - public
      - private
    Description: "Will this service be public facing or in a private network layer?"  
  HealthCheckType:
    Type: String
    Default: ELB
    AllowedValues:
      - EC2
      - ELB
  NexusVersion:
    Type: String    
    Description: "Version of Nexus OSS Repository installation package"
  Scaling:
    Type: CommaDelimitedList
    Description: "Scaling dimensions of the Autoscaling Group - min, max, desired"
  OrgCode:
    Type: String
    Description: "The organization code of the service provider."
  Owner:
    Type: String    
    Description: "The administrator of this instance's email address"
  ServiceDesc:
    Type: String
    Description: "The service description"
  ServiceName:
    Type: String
    Description: "Service name referenced in various resources"
  ServiceProfile:
    Type: String
    Description: "The EC2 Role/Profile name"
  VPCStack:
    Type: String
    Default: 'ROTHSMITH-VPC'

Mappings:
  TierMap:
    public:
      scheme: internet-facing
    private:
      scheme: internal

Resources:
  LoadBalancer: # Application Load Balancer
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ["-", [!Ref OrgCode, !Ref ServiceName, !Ref ElbTier]]
      Scheme: !FindInMap
        - TierMap
        - !Ref ElbTier
        - scheme
      SecurityGroups: ['Fn::ImportValue': !Sub '${VPCStack}-PublicInstanceSG']
      Subnets: ['Fn::ImportValue': !Sub '${VPCStack}-PublicSubnet1', 'Fn::ImportValue': !Sub '${VPCStack}-PublicSubnet2']
      Type: application
      Tags:
      - Key: Name
        Value: !Ref ServiceName
  LoadBalancerListener: 
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref ElbPort
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref Ec2Port
      Protocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 5
      HealthCheckPath: "/"
      HealthCheckPort: !Ref Ec2Port
      HealthCheckIntervalSeconds: 10
      Name: !Join ["-", [!Ref OrgCode, !Ref ServiceName, !Ref ElbTier, "TG"]]
      VpcId: 
        'Fn::ImportValue': 
          !Sub '${VPCStack}-VPCID'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60

  NexusLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata: 
      AWS::CloudFormation::Authentication:  
        S3AccessCreds:  
            type: "S3"  
            roleName: !Ref ServiceProfile  
            buckets:  
                - "rothsmith-iac"
                - "rothsmith-software"
      AWS::CloudFormation::Init: 
        configSets:
          nexus: 
            - "install"
            - "finish"
        install:
          packages: 
            yum: 
              java-1.8.0-openjdk: []  
              polkit: []
          users: 
            nexus: 
              groups: 
                - "users"
              uid: "200"
              homeDir: "/opt/nexus"
          files:
            /tmp/nexus.tar.gz: 
              source: !Join ["", ["https://s3.amazonaws.com/rothsmith-software/nexus-", !Ref NexusVersion, "-unix.tar.gz"]]
              mode: "000744"
              owner: "root"
              group: "root"
              authentication: "S3AccessCreds"
            /etc/systemd/system/nexus.service: 
              content: !Sub | 
               [Unit]
               Description=Sonatype Nexus Repository Manager
               After=network.target
               
               [Service]
               Type=forking
               ExecStart=/opt/nexus/bin/nexus start
               ExecStop=/opt/nexus/bin/nexus stop
               User=nexus
               Restart=on-abort
               #Environment=INSTALL4J_JAVA_HOME=/foo/bar/jre8
               LimitNOFILE=65536
               
               [Install]
               WantedBy=multi-user.target
              mode: "000644"
              owner: "root"
              group: "root"  
          commands:
            1-install-nexus:
              command: !Sub | 
                mkdir /opt/nexus-dir
                tar -xvf /tmp/nexus.tar.gz -C /opt/nexus-dir
                ln -s /opt/nexus-dir/nexus-${NexusVersion} /opt/nexus-current
                ln -s /opt/nexus-current /opt/nexus
                chown -R nexus:nexus /opt/nexus*
                #rm -rf /tmp/nexus*
          services: 
            sysvinit: 
              nexus: 
                enabled: "true"
                ensureRunning: "true"
        finish:
          commands:
            1-signal-success:
              command: !Sub |
                /opt/aws/bin/cfn-signal -e 0 \
                --stack ${AWS::StackName} \
                --resource NexusASG \
                --region=${AWS::Region} \
                --url=https://cloudformation.${AWS::Region}.amazonaws.com
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref ServiceProfile
      InstanceType: !Ref Ec2Type
      ImageId: !Ref AmiId
      KeyName: RothsmithKeyPair
      SecurityGroups: ['Fn::ImportValue': !Sub '${VPCStack}-PrivateSubnetInstanceSG']
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          /opt/aws/bin/cfn-init -v -c nexus \
          -s ${AWS::StackName} \
          --resource NexusLaunchConfiguration \
          --region=${AWS::Region} \
          --url=https://cloudformation.${AWS::Region}.amazonaws.com          
  NexusASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref NexusLaunchConfiguration
      DesiredCapacity: !Select [ "2", !Ref Scaling ]
      HealthCheckGracePeriod: 600
      #LoadBalancerNames:
      #- Ref: LoadBalancer
      TargetGroupARNs: 
        - !Ref TargetGroup
      MinSize: !Select [ "0", !Ref Scaling ]
      MaxSize: !Select [ "1", !Ref Scaling ]
      VPCZoneIdentifier: ['Fn::ImportValue': !Sub '${VPCStack}-PrivateSubnet1', 'Fn::ImportValue': !Sub '${VPCStack}-PrivateSubnet2']
      HealthCheckType: !Ref HealthCheckType
      Tags:
        - Key: Name
          Value: !Ref ServiceName
          PropagateAtLaunch: "true"
        - Key: Owner
          Value: !Ref Owner
          PropagateAtLaunch: "true"
        - Key: Description
          Value: !Ref ServiceDesc
          PropagateAtLaunch: "true"
    UpdatePolicy:
      AutoScalingRollingUpdates:
          MaxBatchSize: 1
          MinInstancesInService: 1          
          PauseTime: PT10M
          WaitOnResourceSignals: true
    CreationPolicy:
      ResourceSignal:
          Count: '1'
          Timeout: PT10M 
Outputs:
  NlbDnsName:
    Description: "Load Balancer Resource"
    Value: !Ref LoadBalancer
  NlbDnsName:
    Description: "DNS Name for Elastic Load Balancer"
    Value: !GetAtt LoadBalancer.DNSName
  NlbZoneId:
    Description: "The ID of the Amazon Route 53 hosted zone associated with the load balancer"
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID
